# Generated by Django 5.2.8 on 2025-11-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_image',
            field=models.FileField(upload_to='clients/'),
        ),
    ]
